services:
  - type: web
    name: resto-v3.5
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: HawkerOps
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_LEVEL
        value: error
      - key: APP_KEY
        generateValue: true
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: database
      - key: DB_CONNECTION
        value: pgsql
      - key: NEON_DB
        sync: false
